id: P004540
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC374
  title: གསུང་འབུམ། ཤེས་རབ་རྒྱལ་མཚན། ༼གློག་ཀླད་པར་མ།༽
  author: ''
  volumes:
    cd830a3dd1f44e8daeea33f84ef529fc:
      image_group_id: I4PD2724
      title: ''
      volume_number: 1
      total_pages: 366
      base_file: v001.txt
    97b9366d7f7b4efb889bb5957aa4d6cd:
      image_group_id: I4PD2725
      title: ''
      volume_number: 2
      total_pages: 630
      base_file: v002.txt
    aff20d2be13b4cea917a3bc08c9c6928:
      image_group_id: I4PD2726
      title: ''
      volume_number: 3
      total_pages: 386
      base_file: v003.txt
    38baf57fe71b4364a85627aa5563592e:
      image_group_id: I4PD2727
      title: ''
      volume_number: 4
      total_pages: 476
      base_file: v004.txt
    dce85ab1777c4fc59d419d13930806c3:
      image_group_id: I4PD2728
      title: ''
      volume_number: 5
      total_pages: 406
      base_file: v005.txt
    3a23aeb54a4c4bbdb5dc628205108a04:
      image_group_id: I4PD2729
      title: ''
      volume_number: 6
      total_pages: 526
      base_file: v006.txt
    0f9632fa33b6430b8cf045caff87e4d0:
      image_group_id: I4PD2730
      title: ''
      volume_number: 7
      total_pages: 364
      base_file: v007.txt
    cdd31784e2334b628bb439debfffc104:
      image_group_id: I4PD2731
      title: ''
      volume_number: 8
      total_pages: 402
      base_file: v008.txt
    f886318068a34f418704b05582db042c:
      image_group_id: I4PD2732
      title: ''
      volume_number: 9
      total_pages: 382
      base_file: v009.txt
    3b4547f800a345a3b0aaeec546ffd34c:
      image_group_id: I4PD2733
      title: ''
      volume_number: 10
      total_pages: 378
      base_file: v010.txt
    9c048c1cade6413c838b065f3e798acb:
      image_group_id: I4PD2734
      title: ''
      volume_number: 11
      total_pages: 428
      base_file: v011.txt
    aff78043420d47239387f3fa7a555c60:
      image_group_id: I4PD2735
      title: ''
      volume_number: 12
      total_pages: 366
      base_file: v012.txt
    8a638c41022f4439a622ae4da53ed793:
      image_group_id: I4PD2736
      title: ''
      volume_number: 13
      total_pages: 376
      base_file: v013.txt
