id: IF3AEEA4D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T17:22:26+00:00'
last_modified: '2022-06-08T01:48:16.065538+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC374
  title: གསུང་འབུམ། ཤེས་རབ་རྒྱལ་མཚན། ༼གློག་ཀླད་པར་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    6FFC:
      image_group_id: I4PD2724
      title: ''
      total_pages: 366
      order: 1
      base_file: 6FFC.txt
    FC73:
      image_group_id: I4PD2725
      title: ''
      total_pages: 630
      order: 2
      base_file: FC73.txt
    '9749':
      image_group_id: I4PD2726
      title: ''
      total_pages: 386
      order: 3
      base_file: 9749.txt
    3A04:
      image_group_id: I4PD2727
      title: ''
      total_pages: 476
      order: 4
      base_file: 3A04.txt
    '8967':
      image_group_id: I4PD2728
      title: ''
      total_pages: 406
      order: 5
      base_file: 8967.txt
    '3087':
      image_group_id: I4PD2729
      title: ''
      total_pages: 526
      order: 6
      base_file: 3087.txt
    '3404':
      image_group_id: I4PD2730
      title: ''
      total_pages: 364
      order: 7
      base_file: 3404.txt
    FAF1:
      image_group_id: I4PD2731
      title: ''
      total_pages: 402
      order: 8
      base_file: FAF1.txt
    4DA9:
      image_group_id: I4PD2732
      title: ''
      total_pages: 382
      order: 9
      base_file: 4DA9.txt
    ACBC:
      image_group_id: I4PD2733
      title: ''
      total_pages: 378
      order: 10
      base_file: ACBC.txt
    3C28:
      image_group_id: I4PD2734
      title: ''
      total_pages: 428
      order: 11
      base_file: 3C28.txt
    FBB7:
      image_group_id: I4PD2735
      title: ''
      total_pages: 366
      order: 12
      base_file: FBB7.txt
    313A:
      image_group_id: I4PD2736
      title: ''
      total_pages: 376
      order: 13
      base_file: 313A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
